if(Investments.find().count()===0){
	Investments.insert({
		type:'基金',
		name:'国泰互联网+',
		income:29000
	});
	Investments.insert({
		type:'基金',
		name:'坚信大安全战略精选',
		income:89000
	});
	Investments.insert({
		type:'股票',
		name:'中国神车',
		income:290
	});
	Investments.insert({
		type:'艺术品',
		name:'行进中的人',
		income:25000
	});
	Investments.insert({
		type:'艺术品',
		name:'扭曲的口香糖',
		income:25000
	});
	Investments.insert({
		type:'股票',
		name:'神牛组合+',
		income:25000
	});
	Investments.insert({
		type:'艺术品',
		name:'奔跑的羊',
		income:25000
	})

}